### ISSUE TITLE
does not build with any current rust release

### ISSUE THREAD

**Issue by matthiaskrgr** [kdy1/flatten#2]
the crate does not build with stable 1.32, beta 1.33 or nightly 1.34.

````
  Compiling flatten v0.2.1 (/tmp/flatten)
warning: unknown lint: `auto_impl`
  --> src/cons/mod.rs:24:9
   |
24 | #[allow(auto_impl)]
   |         ^^^^^^^^^
   |
   = note: #[warn(unknown_lints)] on by default

warning: unknown lint: `auto_impl`
   --> src/into_cons.rs:141:9
    |
141 | #[allow(auto_impl)]
    |         ^^^^^^^^^

error: `impl Trait for .. {}` is an obsolete syntax
  --> src/cons/mod.rs:25:1
   |
25 | impl ValidHead for ..{}
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: use `auto trait Trait {}` instead

error: `impl Trait for .. {}` is an obsolete syntax
   --> src/into_cons.rs:142:1
    |
142 | impl NotTuple for ..{}
    | ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: use `auto trait Trait {}` instead

error[E0554]: #![feature] may not be used on the stable release channel
 --> src/lib.rs:1:1
  |
1 | #![feature(optin_builtin_traits, on_unimplemented, never_type, specialization)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `flatten`.

````

**Comment by kdy1** [comment]
@matthiaskrgr Fixed it and published flatten@0.2.2
